### ISSUE TITLE
Is it a bug? When adding  variable "extent" from colon_s into finalfit() model, the odds ratio cannot be displayed correctly.

### ISSUE THREAD

**Issue by zhaohongxin0** [ewenharrison/finalfit#78] opened 2022-09-05 14:54 UTC
```
explanatory = c("age.factor","extent" , "sex.factor", "obstruct.factor", "perfor.factor")
dependent = "mort_5yr"

t<-colon_s %>%
  finalfit(dependent, explanatory)

t
```
The results are:

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

Dependent: Mortality 5 year |   | Alive | Died | OR (univariable) | OR (multivariable)
-- | -- | -- | -- | -- | --
Age | <40 years | 31 (46.3) | 36 (53.7) | - | -
  | 40-59 years | 208 (61.4) | 131 (38.6) | 0.54 (0.32-0.92, p=0.023) | 0.54 (0.31-0.93, p=0.027)
  | 60+ years | 272 (53.4) | 237 (46.6) | 0.75 (0.45-1.25, p=0.270) | 0.77 (0.45-1.31, p=0.340)
extent | 1 | 16 (80.0) | 4 (20.0) | - | -
  | 2 | 78 (75.7) | 25 (24.3) | - | -
  | 3 | 401 (53.5) | 349 (46.5) | - | -
  | 4 | 16 (38.1) | 26 (61.9) | - | -
Sex | Female | 243 (55.6) | 194 (44.4) | - | -
  | Male | 268 (56.1) | 210 (43.9) | 0.98 (0.76-1.27, p=0.889) | 0.97 (0.74-1.28, p=0.852)
Obstruction | No | 408 (56.7) | 312 (43.3) | - | -
  | Yes | 89 (51.1) | 85 (48.9) | 1.25 (0.90-1.74, p=0.189) | 1.20 (0.86-1.69, p=0.284)
Perforation | No | 497 (56.0) | 391 (44.0) | - | -
  | Yes | 14 (51.9) | 13 (48.1) | 1.18 (0.54-2.55, p=0.672) | 0.98 (0.45-2.16, p=0.970)
NA | NA | NA | NA | 2.22 (1.64-3.07, p<0.001) | 2.25 (1.64-3.14, p<0.001)

</body>

</html>

it seems that the last row is the OR for "extent" as a continuous variable, but in the table, extent is considered as a factor but the OR is not displayed.
If I changed “extent” to a factor, it can be corrected. But how can I do when I want to do it as a continuous variable? cont_cut  seems not work in finalfit().

**Comment by ewenharrison** [comment] 2022-12-16 15:09
Many thanks for this. Apologies I didn't get a notification when this was posted. 

It's kind of a bug, yes, in that a continuous variable with very few distinct values is being passed to a regression model. This would often be treated as a factor (see `extent.factor`). 

I fix for this has been pushed with version 1.0.55. 

Many thanks again,

**Closed by ewenharrison** 2022-12-16 15:10 UTC

**Comment by HoangAVu** [comment] 2023-03-28 23:09
Hi! Can this be extended to or_plot() as well (adding a cont_cut arg)? My finalfit and or_plot are showing incohesive results, most likely because of this reason which causes one of my cont variables to be treated as factor.

**Comment by zhaohongxin0** [comment] 2023-03-31 17:21
I also want to know the updates.
cont_cut now is available in finalfit(), but it doesn't work in glmuni() or glmmulti(). That means we cannot get right results from a poisson model
